### ISSUE TITLE
Is there gonna be a "Import Module"

### ISSUE THREAD

**Issue by Crackerinho** [ArditXhaferi/5HQ1P#2]
I was wondering if you will add the import module like in python for example : "import (lib)"
I wanted to make some libraries for 5HQ1P and play around with it

**Comment by Crackerinho** [comment]
I was also trying to make a syntax highlighter (vscode extension) for 5HQ1P and maybe intellisense after that.

**Comment by ArditXhaferi** [comment]
Yes we have something like Import
Run-Zbato
Tani me deklaratën Zbato ne mund të ekzekutojmë kodin tonë nga files e jashtëm.

```
index.sq > printo("Pershendetje bote")

# Execute our file
shqip > zbato("index.sq")
Pershendetje bot
```

And thank you for the making the vscode extension update me on any news on that would love to see it.

**Comment by Crackerinho** [comment]
Oh I never realized that and yes I'm trying to get it as close to perfect!
Glad someone finally made a programming language in Albanian
