### ISSUE TITLE
PLY

### ISSUE THREAD

**Issue by hedho** [ArditXhaferi/5HQ1P#3]
Me e bo gjuhen tonde prej ‘python’, po mire shume.

Ama pse jo dicka krejt e re ‘shqip’ e pa bazuar ne ndonje gjuhe programuese tjeter 😊.

# Pune t’mare pres nje “geniune from scratch language called SQ”.

Kerkese si feature for the future.

**Comment by ArditXhaferi** [comment]
Pershendetje @hedho ,

Faleminderit per idejen edhe pergzimin, plani in the future eshte me bo gjuhen jo prej scratch(would be to hard to write in 1 and 0s 😆) but me u bo gjuha ne C si shum do gjuh tjera moderne si p.sh Python.

**Comment by hedho** [comment]
> Pershendetje @hedho ,
> 
> Faleminderit per idejen edhe pergzimin, plani in the future eshte me bo gjuhen jo prej scratch(would be to hard to write in 1 and 0s 😆) but me u bo gjuha ne C si shum do gjuh tjera moderne si p.sh Python.

Qekjo isht kon edhe shume ma mire bile :)
